<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MembreSeeder extends Seeder
{
    public function run(): void
    {
        $membres = [
            ['prenom' => 'Kofi',      'nom' => 'Asante',        'email' => 'kofi.asante@email.com',      'telephone' => '+225 07 11 22 33', 'ville' => 'Abidjan',        'secteur' => 'Finance',               'promotion_aiesec' => '2018', 'bio' => 'Directeur financier passionné par l\'entrepreneuriat et l\'impact social en Afrique de l\'Ouest.', 'competences' => ['Analyse financière', 'Comptabilité', 'Excel', 'Gestion de trésorerie']],
            ['prenom' => 'Aminata',   'nom' => 'Coulibaly',     'email' => 'aminata.coulibaly@email.com', 'telephone' => '+225 07 22 33 44', 'ville' => 'Abidjan',        'secteur' => 'Marketing Digital',     'promotion_aiesec' => '2019', 'bio' => 'Spécialiste en marketing digital et stratégie de contenu pour les marques africaines.', 'competences' => ['SEO', 'Community management', 'Google Ads', 'Copywriting']],
            ['prenom' => 'Yves',      'nom' => 'Traoré',        'email' => 'yves.traore@email.com',       'telephone' => '+225 05 33 44 55', 'ville' => 'Bouaké',         'secteur' => 'Agriculture',           'promotion_aiesec' => '2017', 'bio' => 'Agronome et entrepreneur agricole, fondateur d\'une coopérative de cacao dans le centre de la Côte d\'Ivoire.', 'competences' => ['Agroéconomie', 'Management de coopérative', 'Irrigation']],
            ['prenom' => 'Fatoumata', 'nom' => 'Diallo',        'email' => 'fatoumata.diallo@email.com',  'telephone' => '+225 01 44 55 66', 'ville' => 'Yamoussoukro',   'secteur' => 'Santé',                 'promotion_aiesec' => '2020', 'bio' => 'Médecin généraliste engagée dans l\'accès aux soins en zones rurales.', 'competences' => ['Médecine générale', 'Santé publique', 'Gestion de projets santé']],
            ['prenom' => 'Sébastien', 'nom' => 'N\'Guessan',   'email' => 'sebastien.nguessan@email.com','telephone' => '+225 07 55 66 77', 'ville' => 'Abidjan',        'secteur' => 'Technologie',           'promotion_aiesec' => '2016', 'bio' => 'Développeur full-stack et fondateur d\'une startup fintech à Abidjan.', 'competences' => ['Laravel', 'React', 'API REST', 'AWS', 'Gestion de projet']],
            ['prenom' => 'Marie',     'nom' => 'Bamba',         'email' => 'marie.bamba@email.com',       'telephone' => '+225 05 66 77 88', 'ville' => 'San-Pédro',      'secteur' => 'Commerce International','promotion_aiesec' => '2018', 'bio' => 'Experte en import-export et logistique internationale, spécialisée dans le port de San-Pédro.', 'competences' => ['Logistique', 'Douane', 'Incoterms', 'Négociation commerciale']],
            ['prenom' => 'Ibrahim',   'nom' => 'Ouédraogo',     'email' => 'ibrahim.ouedraogo@email.com', 'telephone' => '+225 07 77 88 99', 'ville' => 'Abidjan',        'secteur' => 'Immobilier',            'promotion_aiesec' => '2015', 'bio' => 'Promoteur immobilier et investisseur spécialisé dans le logement abordable.', 'competences' => ['Promotion immobilière', 'Montage financier', 'Négociation']],
            ['prenom' => 'Awa',       'nom' => 'Koné',          'email' => 'awa.kone@email.com',          'telephone' => '+225 01 88 99 00', 'ville' => 'Abidjan',        'secteur' => 'Éducation',             'promotion_aiesec' => '2021', 'bio' => 'Fondatrice d\'une école primaire privée bilingue dans le quartier de Cocody.', 'competences' => ['Pédagogie', 'Management scolaire', 'Développement de curricula']],
            ['prenom' => 'Patrick',   'nom' => 'Zoro',          'email' => 'patrick.zoro@email.com',      'telephone' => '+225 07 99 00 11', 'ville' => 'Abidjan',        'secteur' => 'BTP',                   'promotion_aiesec' => '2017', 'bio' => 'Ingénieur civil et entrepreneur dans le secteur de la construction durable.', 'competences' => ['Génie civil', 'AutoCAD', 'Gestion de chantier', 'Béton armé']],
            ['prenom' => 'Sylvie',    'nom' => 'Ahoussou',      'email' => 'sylvie.ahoussou@email.com',   'telephone' => '+225 05 00 11 22', 'ville' => 'Daloa',          'secteur' => 'Agroalimentaire',       'promotion_aiesec' => '2019', 'bio' => 'Transformatrice de produits locaux (cajou, noix de coco) et fondatrice d\'une PME agroalimentaire.', 'competences' => ['Transformation alimentaire', 'HACCP', 'Gestion PME', 'Export']],
            ['prenom' => 'Moussa',    'nom' => 'Sanogo',        'email' => 'moussa.sanogo@email.com',     'telephone' => '+225 07 11 33 55', 'ville' => 'Korhogo',        'secteur' => 'Élevage',               'promotion_aiesec' => '2016', 'bio' => 'Éleveur et vétérinaire, spécialiste de la filière bovine dans le nord de la Côte d\'Ivoire.', 'competences' => ['Médecine vétérinaire', 'Gestion de troupeau', 'Agropastoralisme']],
            ['prenom' => 'Clarisse',  'nom' => 'Ehui',          'email' => 'clarisse.ehui@email.com',     'telephone' => '+225 01 22 44 66', 'ville' => 'Abidjan',        'secteur' => 'Droit',                 'promotion_aiesec' => '2018', 'bio' => 'Avocate spécialisée en droit des affaires et droit de l\'OHADA.', 'competences' => ['Droit des affaires', 'OHADA', 'Droit fiscal', 'Arbitrage']],
            ['prenom' => 'Théodore',  'nom' => 'Gbagbo',        'email' => 'theodore.gbagbo@email.com',   'telephone' => '+225 07 33 55 77', 'ville' => 'Abidjan',        'secteur' => 'Médias',                'promotion_aiesec' => '2020', 'bio' => 'Journaliste et producteur de contenu audiovisuel, cofondateur d\'une webTV panafricaine.', 'competences' => ['Journalisme', 'Production vidéo', 'Réseaux sociaux', 'Storytelling']],
            ['prenom' => 'Adjoua',    'nom' => 'Yapi',          'email' => 'adjoua.yapi@email.com',       'telephone' => '+225 05 44 66 88', 'ville' => 'Grand-Bassam',   'secteur' => 'Tourisme',              'promotion_aiesec' => '2017', 'bio' => 'Directrice d\'une agence touristique spécialisée dans le tourisme responsable et culturel.', 'competences' => ['Tourisme durable', 'Gestion hôtelière', 'Anglais', 'Event management']],
            ['prenom' => 'Romuald',   'nom' => 'Tape',          'email' => 'romuald.tape@email.com',      'telephone' => '+225 07 55 77 99', 'ville' => 'Abidjan',        'secteur' => 'Logistique',            'promotion_aiesec' => '2015', 'bio' => 'Directeur logistique avec 10 ans d\'expérience dans la chaîne d\'approvisionnement en Afrique.', 'competences' => ['Supply chain', 'WMS', 'Transport multimodal', 'SAP']],
            ['prenom' => 'Nadia',     'nom' => 'Meité',         'email' => 'nadia.meite@email.com',       'telephone' => '+225 01 66 88 00', 'ville' => 'Abidjan',        'secteur' => 'RH & Consulting',       'promotion_aiesec' => '2019', 'bio' => 'Consultante RH et coach certifiée, accompagnant les dirigeants africains dans leur développement.', 'competences' => ['Recrutement', 'Coaching', 'Formation', 'Assessment center']],
            ['prenom' => 'Landry',    'nom' => 'Gnagne',        'email' => 'landry.gnagne@email.com',     'telephone' => '+225 07 77 99 11', 'ville' => 'Abidjan',        'secteur' => 'Énergies renouvelables','promotion_aiesec' => '2018', 'bio' => 'Ingénieur en énergie solaire, fondateur d\'une startup de kits solaires pour les ménages ruraux.', 'competences' => ['Énergie solaire', 'Installation PV', 'Bilan carbone', 'Financement vert']],
            ['prenom' => 'Christelle','nom' => 'Atchori',       'email' => 'christelle.atchori@email.com','telephone' => '+225 05 88 00 22', 'ville' => 'Abidjan',        'secteur' => 'Mode & Textile',        'promotion_aiesec' => '2021', 'bio' => 'Styliste et créatrice de mode, fondatrice d\'une marque de prêt-à-porter inspirée des tissus africains.', 'competences' => ['Design textile', 'Patronage', 'Gestion de marque', 'E-commerce']],
            ['prenom' => 'Hervé',     'nom' => 'Brou',          'email' => 'herve.brou@email.com',        'telephone' => '+225 07 99 11 33', 'ville' => 'Abidjan',        'secteur' => 'Banque',                'promotion_aiesec' => '2016', 'bio' => 'Cadre bancaire spécialisé en financement de projets et en analyse de risques crédit.', 'competences' => ['Crédit analyse', 'Financement de projet', 'Bâle III', 'Scoring']],
            ['prenom' => 'Fatou',     'nom' => 'Sylla',         'email' => 'fatou.sylla@email.com',       'telephone' => '+225 01 00 22 44', 'ville' => 'Man',            'secteur' => 'Artisanat',             'promotion_aiesec' => '2020', 'bio' => 'Artisane et entrepreneuse, fondatrice d\'une coopérative de femmes artisanes à l\'ouest du pays.', 'competences' => ['Artisanat', 'Gestion coopérative', 'Design produit', 'Vente en ligne']],
            ['prenom' => 'Armand',    'nom' => 'Koffi',         'email' => 'armand.koffi@email.com',      'telephone' => '+225 07 11 44 77', 'ville' => 'Abidjan',        'secteur' => 'Assurance',             'promotion_aiesec' => '2017', 'bio' => 'Courtier en assurance spécialisé en assurance vie et produits d\'épargne pour les PME.', 'competences' => ['Courtage assurance', 'Actuariat', 'Gestion de sinistres', 'Prospection']],
            ['prenom' => 'Mariam',    'nom' => 'Fofana',        'email' => 'mariam.fofana@email.com',     'telephone' => '+225 05 22 55 88', 'ville' => 'Abidjan',        'secteur' => 'ONG / Social',          'promotion_aiesec' => '2019', 'bio' => 'Coordinatrice de projets dans le secteur humanitaire, spécialisée dans la protection de l\'enfance.', 'competences' => ['Gestion de projets', 'Rédaction de rapports', 'Mobilisation communautaire']],
            ['prenom' => 'Wilfried',  'nom' => 'Dago',          'email' => 'wilfried.dago@email.com',     'telephone' => '+225 07 33 66 99', 'ville' => 'Abidjan',        'secteur' => 'Informatique',          'promotion_aiesec' => '2016', 'bio' => 'Architecte systèmes et expert cybersécurité pour les entreprises de la sous-région.', 'competences' => ['Cybersécurité', 'Architecture SI', 'Pentest', 'ISO 27001']],
            ['prenom' => 'Estelle',   'nom' => 'N\'Dri',        'email' => 'estelle.ndri@email.com',      'telephone' => '+225 01 44 77 00', 'ville' => 'Abidjan',        'secteur' => 'Restauration',          'promotion_aiesec' => '2021', 'bio' => 'Cheffe cuisinière et restauratrice, promotrice de la gastronomie ivoirienne sur la scène internationale.', 'competences' => ['Cuisine africaine', 'Gestion de restaurant', 'HACCP', 'Management d\'équipe']],
            ['prenom' => 'Bertrand',  'nom' => 'Tanoh',         'email' => 'bertrand.tanoh@email.com',    'telephone' => '+225 07 55 88 11', 'ville' => 'Divo',           'secteur' => 'Hévéaculture',          'promotion_aiesec' => '2015', 'bio' => 'Planteur d\'hévéa et formateur technique pour les petits producteurs de la région de Divo.', 'competences' => ['Hévéaculture', 'Formation agricole', 'Coopérative', 'Certification FSC']],
            ['prenom' => 'Ines',      'nom' => 'Kouakou',       'email' => 'ines.kouakou@email.com',      'telephone' => '+225 05 66 99 22', 'ville' => 'Abidjan',        'secteur' => 'Pharmaceutique',        'promotion_aiesec' => '2018', 'bio' => 'Pharmacienne et entrepreneuse dans la distribution de médicaments essentiels en zone périurbaine.', 'competences' => ['Pharmacie', 'Réglementation médicament', 'Gestion stock', 'Conseil patient']],
            ['prenom' => 'Serge',     'nom' => 'Aka',           'email' => 'serge.aka@email.com',         'telephone' => '+225 07 77 00 33', 'ville' => 'Abidjan',        'secteur' => 'Transport',             'promotion_aiesec' => '2017', 'bio' => 'Entrepreneur dans le transport urbain et la mobilité durable à Abidjan.', 'competences' => ['Mobilité urbaine', 'Gestion de flotte', 'Transport en commun', 'Planification']],
            ['prenom' => 'Cécile',    'nom' => 'Aboua',         'email' => 'cecile.aboua@email.com',      'telephone' => '+225 01 88 11 44', 'ville' => 'Abidjan',        'secteur' => 'Beauté & Cosmétique',   'promotion_aiesec' => '2020', 'bio' => 'Fondatrice d\'une gamme de cosmétiques naturels à base de plantes africaines.', 'competences' => ['Formulation cosmétique', 'Branding', 'Vente directe', 'Réseaux sociaux']],
            ['prenom' => 'Olivier',   'nom' => 'Goba',          'email' => 'olivier.goba@email.com',      'telephone' => '+225 07 99 22 55', 'ville' => 'Abidjan',        'secteur' => 'Imprimerie',            'promotion_aiesec' => '2016', 'bio' => 'Directeur d\'une imprimerie numérique et d\'une agence de communication visuelle.', 'competences' => ['Imprimerie', 'Infographie', 'Illustrator', 'Gestion de production']],
            ['prenom' => 'Danielle',  'nom' => 'Bah',           'email' => 'danielle.bah@email.com',      'telephone' => '+225 05 00 33 66', 'ville' => 'Abidjan',        'secteur' => 'Microfinance',          'promotion_aiesec' => '2019', 'bio' => 'Responsable crédit dans une institution de microfinance, spécialisée dans le financement des femmes entrepreneures.', 'competences' => ['Microfinance', 'Analyse crédit', 'Épargne', 'Inclusion financière']],
        ];

        foreach ($membres as $data) {
            $user = User::create([
                'prenom'           => $data['prenom'],
                'nom'              => $data['nom'],
                'email'            => $data['email'],
                'telephone'        => $data['telephone'],
                'password'         => Hash::make('password'),
                'statut'           => User::STATUT_ACTIF,
                'ville'            => $data['ville'],
                'secteur'          => $data['secteur'],
                'promotion_aiesec' => $data['promotion_aiesec'],
                'bio'              => $data['bio'],
                'competences'      => $data['competences'],
                'date_validation'  => now()->subDays(rand(10, 365)),
            ]);

            $user->assignRole('membre');
        }

        $this->command->info('30 membres créés avec succès.');
    }
}
