<?php

return [
    'Agriculture & Agroalimentaire',
    'Banque & Finance',
    'BTP & Immobilier',
    'Commerce & Distribution',
    'Communication & Marketing',
    'Consulting & Stratégie',
    'Culture & Arts',
    'Droit & Juridique',
    'Éducation & Formation',
    'Énergie & Environnement',
    'Hôtellerie & Tourisme',
    'Humanitaire & ONG',
    'Industrie & Manufacture',
    'Informatique & Télécoms',
    'Logistique & Transport',
    'Médias & Journalisme',
    'Médical & Santé',
    'Mines & Ressources naturelles',
    'Mode & Textile',
    'Recherche & Innovation',
    'Ressources humaines',
    'Restauration & Food',
    'Sécurité & Défense',
    'Services publics & Administration',
    'Sport & Bien-être',
    'Autre',
];
